### ISSUE TITLE
Lists of videos are not correctly sorted by their dates

### ISSUE THREAD

**Issue by ittipatken** [docchula/FlickPlayer#15]
![image](https://github.com/docchula/FlickPlayer/assets/39715559/4d09fdae-14fb-4179-b192-931b3ac492a7)

**Comment by keenthekeen** [comment]
should be fixed by [#5fe5b73646275ef2b824df2a493e4b683196ed77](https://github.com/docchula/FlickPlayer/commit/5fe5b73646275ef2b824df2a493e4b683196ed77)
