### ISSUE TITLE
Notify users that they need to subscribe to the courses to view them

### ISSUE THREAD

**Issue by ittipatken** [docchula/FlickPlayer#7]
Many users do not know that they need to subscribe on the main E-learning website.

**Comment by keenthekeen** [comment]
They don't need to.

Are you referring to what's mentioned in [FlickMan](https://github.com/docchula/FlickMan)'s readme? Only the E-Learning user whom credential FlickMan used to crawls video indexes needs to subscribe to each course. Subscription is not required for end users.

**Comment by ittipatken** [comment]
Yes, I misunderstood the FlickMan's readme. I apologize for any confusion. However, the problem should be incomplete collection of lectures (users do not have access to some of the old lectures).
