### ISSUE TITLE
Update Video.js

### ISSUE THREAD

**Issue by ittipatken** [docchula/FlickPlayer#8]
Purpose of this issue is for tracking. I think Video.js@8.61 is not fully compatible with Angular yet. (https://github.com/videojs/video.js/issues/8141#issuecomment-1821175130)

**Comment by keenthekeen** [comment]
Upgraded to video.js 8 in https://github.com/docchula/FlickPlayer/commit/1e083a8e7a33010a642508ffc3d759d67f9627b0
